version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./deployment/docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/backend
    ports:
      - 8000:8000
    env_file:
      - ./backend/config/.env
    depends_on:
      - database

  database:
    container_name: database
    image: postgis/postgis:15-3.3-alpine
    env_file:
      - ./backend/config/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  redis:
    container_name: redis
    image: redis:alpine
    env_file:
      - ./backend/config/.env
    expose:
      - 6379

  celery-worker:
    container_name: celery-worker
    build:
      context: ./
      dockerfile: ./deployment/docker/Dockerfile
    command: celery -A college_enrolment_system worker -l info
    volumes:
      - ./backend/:/backend
    env_file:
      - ./backend/config/.env
    depends_on:
      - database
      - redis

  celery-beat:
    container_name: celery-beat
    build:
      context: ./
      dockerfile: ./deployment/docker/Dockerfile
    command: celery -A college_enrolment_system beat -l info
    volumes:
      - ./backend/:/backend
    env_file:
      - ./backend/config/.env
    depends_on:
      - database
      - redis
      - celery-worker

volumes:
  postgres-data: