# Generated by Django 5.0.6 on 2024-07-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0003_alter_application_offer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offerstage",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="offerstage",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
